Dim oAnsoftApp
Dim oDesktop
Dim oProject
Dim oDesign
Dim oEditor
Dim oModule
Set oAnsoftApp = CreateObject("AnsoftHfss.HfssScriptInterface")
Set oDesktop = oAnsoftApp.GetAppDesktop()
Set oProject = oDesktop.GetActiveProject ()
Set oDesign = oProject.GetActiveDesign ()
Set oEditor = oDesign.SetActiveEditor("3D Modeler")
oEditor.CreateCylinder Array("NAME:CylinderParameters", "XCenter:=", "-3.0mm", "YCenter:=", "0mm", "ZCenter:=", "0mm", "Radius:=", "0.4mm", "Height:=", "3.15mm", "WhichAxis:=", "Z", "NumSides:=", "0"), Array("NAME:Attributes", "Name:=", "via0", "Flags:=", "",   "Color:=", "(132 132 193)", "Transparency:=", 0.400000005960464, "PartCoordinateSystem:=",  "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", true)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:Geometry3DAttributeTab", Array("NAME:PropServers","via0"), Array("NAME:ChangedProps", Array("NAME:Material", "Value:=", "" & Chr(34) & "pec" & Chr(34) & ""))))
oEditor.CreateCylinder Array("NAME:CylinderParameters", "XCenter:=", "-3.07882562659mm", "YCenter:=", "1mm", "ZCenter:=", "0mm", "Radius:=", "0.4mm", "Height:=", "3.15mm", "WhichAxis:=", "Z", "NumSides:=", "0"), Array("NAME:Attributes", "Name:=", "via1", "Flags:=", "",   "Color:=", "(132 132 193)", "Transparency:=", 0.400000005960464, "PartCoordinateSystem:=",  "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", true)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:Geometry3DAttributeTab", Array("NAME:PropServers","via1"), Array("NAME:ChangedProps", Array("NAME:Material", "Value:=", "" & Chr(34) & "pec" & Chr(34) & ""))))
oEditor.CreateCylinder Array("NAME:CylinderParameters", "XCenter:=", "-3.1638647326mm", "YCenter:=", "2mm", "ZCenter:=", "0mm", "Radius:=", "0.4mm", "Height:=", "3.15mm", "WhichAxis:=", "Z", "NumSides:=", "0"), Array("NAME:Attributes", "Name:=", "via2", "Flags:=", "",   "Color:=", "(132 132 193)", "Transparency:=", 0.400000005960464, "PartCoordinateSystem:=",  "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", true)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:Geometry3DAttributeTab", Array("NAME:PropServers","via2"), Array("NAME:ChangedProps", Array("NAME:Material", "Value:=", "" & Chr(34) & "pec" & Chr(34) & ""))))
oEditor.CreateCylinder Array("NAME:CylinderParameters", "XCenter:=", "-3.25560709941mm", "YCenter:=", "3mm", "ZCenter:=", "0mm", "Radius:=", "0.4mm", "Height:=", "3.15mm", "WhichAxis:=", "Z", "NumSides:=", "0"), Array("NAME:Attributes", "Name:=", "via3", "Flags:=", "",   "Color:=", "(132 132 193)", "Transparency:=", 0.400000005960464, "PartCoordinateSystem:=",  "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", true)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:Geometry3DAttributeTab", Array("NAME:PropServers","via3"), Array("NAME:ChangedProps", Array("NAME:Material", "Value:=", "" & Chr(34) & "pec" & Chr(34) & ""))))
oEditor.CreateCylinder Array("NAME:CylinderParameters", "XCenter:=", "-3.35458111578mm", "YCenter:=", "4mm", "ZCenter:=", "0mm", "Radius:=", "0.4mm", "Height:=", "3.15mm", "WhichAxis:=", "Z", "NumSides:=", "0"), Array("NAME:Attributes", "Name:=", "via4", "Flags:=", "",   "Color:=", "(132 132 193)", "Transparency:=", 0.400000005960464, "PartCoordinateSystem:=",  "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", true)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:Geometry3DAttributeTab", Array("NAME:PropServers","via4"), Array("NAME:ChangedProps", Array("NAME:Material", "Value:=", "" & Chr(34) & "pec" & Chr(34) & ""))))
oEditor.CreateCylinder Array("NAME:CylinderParameters", "XCenter:=", "-3.46135682101mm", "YCenter:=", "5mm", "ZCenter:=", "0mm", "Radius:=", "0.4mm", "Height:=", "3.15mm", "WhichAxis:=", "Z", "NumSides:=", "0"), Array("NAME:Attributes", "Name:=", "via5", "Flags:=", "",   "Color:=", "(132 132 193)", "Transparency:=", 0.400000005960464, "PartCoordinateSystem:=",  "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", true)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:Geometry3DAttributeTab", Array("NAME:PropServers","via5"), Array("NAME:ChangedProps", Array("NAME:Material", "Value:=", "" & Chr(34) & "pec" & Chr(34) & ""))))
oEditor.CreateCylinder Array("NAME:CylinderParameters", "XCenter:=", "-3.5765491881mm", "YCenter:=", "6mm", "ZCenter:=", "0mm", "Radius:=", "0.4mm", "Height:=", "3.15mm", "WhichAxis:=", "Z", "NumSides:=", "0"), Array("NAME:Attributes", "Name:=", "via6", "Flags:=", "",   "Color:=", "(132 132 193)", "Transparency:=", 0.400000005960464, "PartCoordinateSystem:=",  "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", true)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:Geometry3DAttributeTab", Array("NAME:PropServers","via6"), Array("NAME:ChangedProps", Array("NAME:Material", "Value:=", "" & Chr(34) & "pec" & Chr(34) & ""))))
oEditor.CreateCylinder Array("NAME:CylinderParameters", "XCenter:=", "-3.70082166571mm", "YCenter:=", "7mm", "ZCenter:=", "0mm", "Radius:=", "0.4mm", "Height:=", "3.15mm", "WhichAxis:=", "Z", "NumSides:=", "0"), Array("NAME:Attributes", "Name:=", "via7", "Flags:=", "",   "Color:=", "(132 132 193)", "Transparency:=", 0.400000005960464, "PartCoordinateSystem:=",  "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", true)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:Geometry3DAttributeTab", Array("NAME:PropServers","via7"), Array("NAME:ChangedProps", Array("NAME:Material", "Value:=", "" & Chr(34) & "pec" & Chr(34) & ""))))
oEditor.CreateCylinder Array("NAME:CylinderParameters", "XCenter:=", "-3.83488999923mm", "YCenter:=", "8mm", "ZCenter:=", "0mm", "Radius:=", "0.4mm", "Height:=", "3.15mm", "WhichAxis:=", "Z", "NumSides:=", "0"), Array("NAME:Attributes", "Name:=", "via8", "Flags:=", "",   "Color:=", "(132 132 193)", "Transparency:=", 0.400000005960464, "PartCoordinateSystem:=",  "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", true)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:Geometry3DAttributeTab", Array("NAME:PropServers","via8"), Array("NAME:ChangedProps", Array("NAME:Material", "Value:=", "" & Chr(34) & "pec" & Chr(34) & ""))))
oEditor.CreateCylinder Array("NAME:CylinderParameters", "XCenter:=", "-3.97952635315mm", "YCenter:=", "9mm", "ZCenter:=", "0mm", "Radius:=", "0.4mm", "Height:=", "3.15mm", "WhichAxis:=", "Z", "NumSides:=", "0"), Array("NAME:Attributes", "Name:=", "via9", "Flags:=", "",   "Color:=", "(132 132 193)", "Transparency:=", 0.400000005960464, "PartCoordinateSystem:=",  "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", true)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:Geometry3DAttributeTab", Array("NAME:PropServers","via9"), Array("NAME:ChangedProps", Array("NAME:Material", "Value:=", "" & Chr(34) & "pec" & Chr(34) & ""))))
oEditor.CreateCylinder Array("NAME:CylinderParameters", "XCenter:=", "-4.1355637583mm", "YCenter:=", "10mm", "ZCenter:=", "0mm", "Radius:=", "0.4mm", "Height:=", "3.15mm", "WhichAxis:=", "Z", "NumSides:=", "0"), Array("NAME:Attributes", "Name:=", "via10", "Flags:=", "",   "Color:=", "(132 132 193)", "Transparency:=", 0.400000005960464, "PartCoordinateSystem:=",  "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", true)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:Geometry3DAttributeTab", Array("NAME:PropServers","via10"), Array("NAME:ChangedProps", Array("NAME:Material", "Value:=", "" & Chr(34) & "pec" & Chr(34) & ""))))
oEditor.CreateCylinder Array("NAME:CylinderParameters", "XCenter:=", "-4.30390090968mm", "YCenter:=", "11mm", "ZCenter:=", "0mm", "Radius:=", "0.4mm", "Height:=", "3.15mm", "WhichAxis:=", "Z", "NumSides:=", "0"), Array("NAME:Attributes", "Name:=", "via11", "Flags:=", "",   "Color:=", "(132 132 193)", "Transparency:=", 0.400000005960464, "PartCoordinateSystem:=",  "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", true)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:Geometry3DAttributeTab", Array("NAME:PropServers","via11"), Array("NAME:ChangedProps", Array("NAME:Material", "Value:=", "" & Chr(34) & "pec" & Chr(34) & ""))))
oEditor.CreateCylinder Array("NAME:CylinderParameters", "XCenter:=", "-4.4855073425mm", "YCenter:=", "12mm", "ZCenter:=", "0mm", "Radius:=", "0.4mm", "Height:=", "3.15mm", "WhichAxis:=", "Z", "NumSides:=", "0"), Array("NAME:Attributes", "Name:=", "via12", "Flags:=", "",   "Color:=", "(132 132 193)", "Transparency:=", 0.400000005960464, "PartCoordinateSystem:=",  "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", true)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:Geometry3DAttributeTab", Array("NAME:PropServers","via12"), Array("NAME:ChangedProps", Array("NAME:Material", "Value:=", "" & Chr(34) & "pec" & Chr(34) & ""))))
oEditor.CreateCylinder Array("NAME:CylinderParameters", "XCenter:=", "-4.68142901617mm", "YCenter:=", "13mm", "ZCenter:=", "0mm", "Radius:=", "0.4mm", "Height:=", "3.15mm", "WhichAxis:=", "Z", "NumSides:=", "0"), Array("NAME:Attributes", "Name:=", "via13", "Flags:=", "",   "Color:=", "(132 132 193)", "Transparency:=", 0.400000005960464, "PartCoordinateSystem:=",  "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", true)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:Geometry3DAttributeTab", Array("NAME:PropServers","via13"), Array("NAME:ChangedProps", Array("NAME:Material", "Value:=", "" & Chr(34) & "pec" & Chr(34) & ""))))
oEditor.CreateCylinder Array("NAME:CylinderParameters", "XCenter:=", "-4.89279433854mm", "YCenter:=", "14mm", "ZCenter:=", "0mm", "Radius:=", "0.4mm", "Height:=", "3.15mm", "WhichAxis:=", "Z", "NumSides:=", "0"), Array("NAME:Attributes", "Name:=", "via14", "Flags:=", "",   "Color:=", "(132 132 193)", "Transparency:=", 0.400000005960464, "PartCoordinateSystem:=",  "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", true)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:Geometry3DAttributeTab", Array("NAME:PropServers","via14"), Array("NAME:ChangedProps", Array("NAME:Material", "Value:=", "" & Chr(34) & "pec" & Chr(34) & ""))))
oEditor.CreateCylinder Array("NAME:CylinderParameters", "XCenter:=", "-5.12082066489mm", "YCenter:=", "15mm", "ZCenter:=", "0mm", "Radius:=", "0.4mm", "Height:=", "3.15mm", "WhichAxis:=", "Z", "NumSides:=", "0"), Array("NAME:Attributes", "Name:=", "via15", "Flags:=", "",   "Color:=", "(132 132 193)", "Transparency:=", 0.400000005960464, "PartCoordinateSystem:=",  "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", true)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:Geometry3DAttributeTab", Array("NAME:PropServers","via15"), Array("NAME:ChangedProps", Array("NAME:Material", "Value:=", "" & Chr(34) & "pec" & Chr(34) & ""))))
oEditor.CreateCylinder Array("NAME:CylinderParameters", "XCenter:=", "-5.36682130928mm", "YCenter:=", "16mm", "ZCenter:=", "0mm", "Radius:=", "0.4mm", "Height:=", "3.15mm", "WhichAxis:=", "Z", "NumSides:=", "0"), Array("NAME:Attributes", "Name:=", "via16", "Flags:=", "",   "Color:=", "(132 132 193)", "Transparency:=", 0.400000005960464, "PartCoordinateSystem:=",  "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", true)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:Geometry3DAttributeTab", Array("NAME:PropServers","via16"), Array("NAME:ChangedProps", Array("NAME:Material", "Value:=", "" & Chr(34) & "pec" & Chr(34) & ""))))
oEditor.CreateCylinder Array("NAME:CylinderParameters", "XCenter:=", "-5.63221310862mm", "YCenter:=", "17mm", "ZCenter:=", "0mm", "Radius:=", "0.4mm", "Height:=", "3.15mm", "WhichAxis:=", "Z", "NumSides:=", "0"), Array("NAME:Attributes", "Name:=", "via17", "Flags:=", "",   "Color:=", "(132 132 193)", "Transparency:=", 0.400000005960464, "PartCoordinateSystem:=",  "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", true)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:Geometry3DAttributeTab", Array("NAME:PropServers","via17"), Array("NAME:ChangedProps", Array("NAME:Material", "Value:=", "" & Chr(34) & "pec" & Chr(34) & ""))))
oEditor.CreateCylinder Array("NAME:CylinderParameters", "XCenter:=", "-5.91852458283mm", "YCenter:=", "18mm", "ZCenter:=", "0mm", "Radius:=", "0.4mm", "Height:=", "3.15mm", "WhichAxis:=", "Z", "NumSides:=", "0"), Array("NAME:Attributes", "Name:=", "via18", "Flags:=", "",   "Color:=", "(132 132 193)", "Transparency:=", 0.400000005960464, "PartCoordinateSystem:=",  "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", true)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:Geometry3DAttributeTab", Array("NAME:PropServers","via18"), Array("NAME:ChangedProps", Array("NAME:Material", "Value:=", "" & Chr(34) & "pec" & Chr(34) & ""))))
oEditor.CreateCylinder Array("NAME:CylinderParameters", "XCenter:=", "-6.2274047384mm", "YCenter:=", "19mm", "ZCenter:=", "0mm", "Radius:=", "0.4mm", "Height:=", "3.15mm", "WhichAxis:=", "Z", "NumSides:=", "0"), Array("NAME:Attributes", "Name:=", "via19", "Flags:=", "",   "Color:=", "(132 132 193)", "Transparency:=", 0.400000005960464, "PartCoordinateSystem:=",  "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", true)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:Geometry3DAttributeTab", Array("NAME:PropServers","via19"), Array("NAME:ChangedProps", Array("NAME:Material", "Value:=", "" & Chr(34) & "pec" & Chr(34) & ""))))
oEditor.CreateCylinder Array("NAME:CylinderParameters", "XCenter:=", "-6.56063256577mm", "YCenter:=", "20mm", "ZCenter:=", "0mm", "Radius:=", "0.4mm", "Height:=", "3.15mm", "WhichAxis:=", "Z", "NumSides:=", "0"), Array("NAME:Attributes", "Name:=", "via20", "Flags:=", "",   "Color:=", "(132 132 193)", "Transparency:=", 0.400000005960464, "PartCoordinateSystem:=",  "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", true)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:Geometry3DAttributeTab", Array("NAME:PropServers","via20"), Array("NAME:ChangedProps", Array("NAME:Material", "Value:=", "" & Chr(34) & "pec" & Chr(34) & ""))))
oEditor.CreateCylinder Array("NAME:CylinderParameters", "XCenter:=", "-6.92012728543mm", "YCenter:=", "21mm", "ZCenter:=", "0mm", "Radius:=", "0.4mm", "Height:=", "3.15mm", "WhichAxis:=", "Z", "NumSides:=", "0"), Array("NAME:Attributes", "Name:=", "via21", "Flags:=", "",   "Color:=", "(132 132 193)", "Transparency:=", 0.400000005960464, "PartCoordinateSystem:=",  "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", true)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:Geometry3DAttributeTab", Array("NAME:PropServers","via21"), Array("NAME:ChangedProps", Array("NAME:Material", "Value:=", "" & Chr(34) & "pec" & Chr(34) & ""))))
oEditor.CreateCylinder Array("NAME:CylinderParameters", "XCenter:=", "-7.30795940163mm", "YCenter:=", "22mm", "ZCenter:=", "0mm", "Radius:=", "0.4mm", "Height:=", "3.15mm", "WhichAxis:=", "Z", "NumSides:=", "0"), Array("NAME:Attributes", "Name:=", "via22", "Flags:=", "",   "Color:=", "(132 132 193)", "Transparency:=", 0.400000005960464, "PartCoordinateSystem:=",  "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", true)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:Geometry3DAttributeTab", Array("NAME:PropServers","via22"), Array("NAME:ChangedProps", Array("NAME:Material", "Value:=", "" & Chr(34) & "pec" & Chr(34) & ""))))
oEditor.CreateCylinder Array("NAME:CylinderParameters", "XCenter:=", "-7.7263626274mm", "YCenter:=", "23mm", "ZCenter:=", "0mm", "Radius:=", "0.4mm", "Height:=", "3.15mm", "WhichAxis:=", "Z", "NumSides:=", "0"), Array("NAME:Attributes", "Name:=", "via23", "Flags:=", "",   "Color:=", "(132 132 193)", "Transparency:=", 0.400000005960464, "PartCoordinateSystem:=",  "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", true)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:Geometry3DAttributeTab", Array("NAME:PropServers","via23"), Array("NAME:ChangedProps", Array("NAME:Material", "Value:=", "" & Chr(34) & "pec" & Chr(34) & ""))))
oEditor.CreateCylinder Array("NAME:CylinderParameters", "XCenter:=", "-8.17774674961mm", "YCenter:=", "24mm", "ZCenter:=", "0mm", "Radius:=", "0.4mm", "Height:=", "3.15mm", "WhichAxis:=", "Z", "NumSides:=", "0"), Array("NAME:Attributes", "Name:=", "via24", "Flags:=", "",   "Color:=", "(132 132 193)", "Transparency:=", 0.400000005960464, "PartCoordinateSystem:=",  "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", true)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:Geometry3DAttributeTab", Array("NAME:PropServers","via24"), Array("NAME:ChangedProps", Array("NAME:Material", "Value:=", "" & Chr(34) & "pec" & Chr(34) & ""))))
oEditor.CreateCylinder Array("NAME:CylinderParameters", "XCenter:=", "-8.66471150809mm", "YCenter:=", "25mm", "ZCenter:=", "0mm", "Radius:=", "0.4mm", "Height:=", "3.15mm", "WhichAxis:=", "Z", "NumSides:=", "0"), Array("NAME:Attributes", "Name:=", "via25", "Flags:=", "",   "Color:=", "(132 132 193)", "Transparency:=", 0.400000005960464, "PartCoordinateSystem:=",  "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", true)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:Geometry3DAttributeTab", Array("NAME:PropServers","via25"), Array("NAME:ChangedProps", Array("NAME:Material", "Value:=", "" & Chr(34) & "pec" & Chr(34) & ""))))
oEditor.CreateCylinder Array("NAME:CylinderParameters", "XCenter:=", "-9.19006156879mm", "YCenter:=", "26mm", "ZCenter:=", "0mm", "Radius:=", "0.4mm", "Height:=", "3.15mm", "WhichAxis:=", "Z", "NumSides:=", "0"), Array("NAME:Attributes", "Name:=", "via26", "Flags:=", "",   "Color:=", "(132 132 193)", "Transparency:=", 0.400000005960464, "PartCoordinateSystem:=",  "Global", "UDMId:=", "", "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=", true)
oEditor.ChangeProperty Array("NAME:AllTabs", Array("NAME:Geometry3DAttributeTab", Array("NAME:PropServers","via26"), Array("NAME:ChangedProps", Array("NAME:Material", "Value:=", "" & Chr(34) & "pec" & Chr(34) & ""))))
